CREATE TABLE order_header (
  order_header_id int(10) unsigned NOT NULL AUTO_INCREMENT,
  user_id int(10) unsigned NOT NULL,
  user_login varchar(50) DEFAULT NULL,
  order_no varchar(100) NOT NULL,
  total_quantity int(10) NOT NULL,
  lead_time int(11) DEFAULT NULL,
  total_amount float(15,3) NOT NULL,
  original_total_amount float(15,3) NOT NULL,
  express_delivery_charge float(15,3) DEFAULT NULL,
  original_express_delivery_charge float(15,3) DEFAULT NULL,
  duties float(15,3) DEFAULT NULL,
  original_duties float(15,3) DEFAULT NULL,
  currency_conversion_rate float(15,3) DEFAULT NULL,
  currency_code varchar(25) DEFAULT NULL,
  currency_symbol_flag int(1) DEFAULT NULL,
  payment_status VARCHAR(25) DEFAULT NULL,
  order_status VARCHAR(25) DEFAULT NULL,
  billing_status VARCHAR(25) DEFAULT NULL,
  billing_first_name varchar(50) DEFAULT NULL,
  billing_middle_name varchar(50) DEFAULT NULL,
  billing_last_name varchar(50) DEFAULT NULL,
  billing_email_address_1 varchar(100) DEFAULT NULL,
  billing_email_address_2 varchar(100) DEFAULT NULL,
  billing_mobile_1 varchar(25) DEFAULT NULL,
  billing_mobile_2 varchar(25) DEFAULT NULL,
  billing_address_line_1 varchar(100) DEFAULT NULL,
  billing_address_line_2 varchar(100) DEFAULT NULL,
  billing_address_line_3 varchar(100) DEFAULT NULL,
  billing_city varchar(25) DEFAULT NULL,
  billing_zip_code varchar(25) DEFAULT NULL,
  billing_state varchar(25) DEFAULT NULL,
  billing_country varchar(25) DEFAULT NULL,
  order_tracking_number varchar(45) DEFAULT NULL,
  order_date date DEFAULT NULL,
  delivery_date date DEFAULT NULL,
  courier_id int(10) unsigned DEFAULT NULL,
  voucher_code varchar(25) DEFAULT NULL,
  voucher_discount_percent float(15,3) DEFAULT NULL,
  voucher_discount_absolute float(15,3) DEFAULT NULL,
  discount_value float(15,3) DEFAULT NULL,
  gift_wrapping_required tinyint(1) DEFAULT NULL,
  order_comments varchar(500) DEFAULT NULL,
  email_regenerated_by varchar(100) DEFAULT NULL,
  promotion_source varchar(100) DEFAULT NULL,
  referer_source varchar(100) DEFAULT NULL,
  payment_status_modifier varchar(100) DEFAULT NULL,
  website_id int(10) DEFAULT NULL,
  created_by varchar(50) NOT NULL,
  created_date datetime NOT NULL,
  modified_by varchar(50) NOT NULL,
  modified_date datetime NOT NULL,
  PRIMARY KEY (order_header_id),
  KEY FK_order_header_1 (user_id),
  KEY FK_order_header_2 (currency_code),
  KEY FK_order_header_3 (courier_id),
  CONSTRAINT FK_order_header_1 FOREIGN KEY (user_id) REFERENCES core_user_master (user_id),
  CONSTRAINT FK_order_header_2 FOREIGN KEY (currency_code) REFERENCES core_currency_master (currency_code),
  CONSTRAINT FK_order_header_3 FOREIGN KEY (courier_id) REFERENCES core_courier_master (courier_id),
  CONSTRAINT FK_order_header_4 FOREIGN KEY (billing_city) REFERENCES core_city_master (city_code),
  CONSTRAINT FK_order_header_5 FOREIGN KEY (billing_state) REFERENCES core_state_master (state_code),
  CONSTRAINT FK_order_header_6 FOREIGN KEY (billing_country) REFERENCES core_country_master (country_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



